plugins {
    id 'java-library'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}

group = 'org.digitalmind'
version = '4.0.0'
ext {
    lombokVersion = '1.18.44'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}
bootJar {
    enabled = false
}
jar {
    archiveBaseName = "signature-cartrige"
    enabled = true
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "digitalmind"
        url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
        credentials {
            username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
            password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    implementation "com.github.librepdf:openpdf:2.0.1"
    implementation 'org.beryx:awt-color-factory:1.0.1'
    implementation 'commons-io:commons-io:2.18.0'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
}

publishing {
    repositories {
        maven {
            name = "digitalmind"
            url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
            credentials {
                username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
                password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
            }
        }
    }
    publications {
        signatureCartrige(MavenPublication) {
            from components.java
        }
    }
}
